/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import type { SoundfontPlayer } from 'soundfont-player';
import type { Stats, Prompt, SessionStats } from './types';
import { DEFAULT_A4_FREQUENCY } from './constants';
import { IInstrument } from './instruments/instrument';
import { instruments } from './instruments';
import type { SessionPace } from './session-pace';
import type { MicSensitivityPreset } from './mic-input-sensitivity';
import type { MicNoteAttackFilterPreset } from './mic-note-attack-filter';
import type { MicNoteHoldFilterPreset, PerformanceMicHoldCalibrationLevel } from './mic-note-hold-filter';
import type { MicPolyphonicDetectorProvider } from './mic-polyphonic-detector';
import type { PerformanceTimelineFeedbackByEvent } from './performance-timeline-feedback';
import type { PerformanceSessionNoteLogSnapshot } from './performance-session-note-log';
import type {
  MicPerformanceOnsetRejectReasonKey,
  PerformanceCaptureEventTelemetry,
  PerformanceOnsetRejectEventLogEntry,
  PerformanceTimingEventLogEntry,
  SessionAnalysisBundle,
} from './session-analysis-bundle';
import type { PerformanceMicTolerancePreset } from './performance-mic-tolerance';
import type { PerformanceTimingLeniencyPreset } from './performance-timing-forgiveness';
import type { AudioInputProcessingSettings } from './audio-runtime';
import type { MelodyFingeringLevel, MelodyFingeringStrategy } from './melody-fingering';
import type { UiWorkflow } from './training-workflows';
import type { UiMode } from './ui-mode';
import { DEFAULT_PROMPT_SOUND_TAIL_MS } from './prompt-sound-tail';

// --- APPLICATION STATE ---
export const state = {
  audioContext: null as AudioContext | null,
  analyser: null as AnalyserNode | null,
  preEmphasisFilter: null as BiquadFilterNode | null,
  microphone: null as MediaStreamAudioSourceNode | null,
  mediaStream: null as MediaStream | null,
  activeAudioInputDeviceId: null as string | null,
  activeAudioInputTrackSettings: null as AudioInputProcessingSettings | null,
  activeAudioInputTrackContentHint: null as string | null,
  requestedAudioInputContentHint: null as string | null,
  dataArray: null as Float32Array | null, // For monophonic (time domain)
  frequencyDataArray: null as Float32Array | null, // For polyphonic (frequency domain)
  isListening: false,
  animationId: 0,
  currentPrompt: null as Prompt | null,
  liveDetectedNote: null as string | null,
  liveDetectedString: null as string | null,
  wrongDetectedNote: null as string | null,
  wrongDetectedString: null as string | null,
  wrongDetectedFret: null as number | null,
  previousNote: null as string | null, // To avoid consecutive identical prompts
  startTime: 0,
  stableNoteCounter: 0,
  lastNote: null as string | null,
  lastDetectedChord: '',
  stableChordCounter: 0,
  monophonicConfidenceEma: 0,
  monophonicVoicingEma: 0,
  consecutiveSilence: 0,
  lastPitches: [] as number[],
  rhythmLastJudgedBeatAtMs: null as number | null,
  showingAllNotes: false,
  autoPlayPromptSound: true,
  promptSoundTailMs: DEFAULT_PROMPT_SOUND_TAIL_MS,
  relaxPerformanceOctaveCheck: true,
  melodyFingeringStrategy: 'minimax' as MelodyFingeringStrategy,
  melodyFingeringLevel: 'beginner' as MelodyFingeringLevel,
  performanceMicTolerancePreset: 'normal' as PerformanceMicTolerancePreset,
  performanceTimingLeniencyPreset: 'normal' as PerformanceTimingLeniencyPreset,
  performanceMicLatencyCompensationMs: 0,
  studyMelodyMicGatePercent: 100,
  studyMelodyMicNoiseGuardPercent: 100,
  studyMelodyMicSilenceResetFrames: 0,
  studyMelodyMicStableFrames: 0,
  studyMelodyPreEmphasisFrequencyHz: 300,
  studyMelodyPreEmphasisGainDb: 5,
  performanceTimingBiasMs: 0,
  performanceTimingBiasSampleCount: 0,
  showMelodyTimelineSteps: false,
  showMelodyTimelineDetails: false,
  cooldown: false,
  ignorePromptAudioUntilMs: 0,
  // --- Mode-specific state (managed by mode classes) ---
  scaleNotes: [] as { note: string; string: string }[],
  currentScaleIndex: 0,
  currentProgression: [] as string[],
  currentProgressionIndex: 0,
  currentArpeggioIndex: 0,
  currentMelodyId: null as string | null,
  currentMelodyEventIndex: 0,
  performanceActiveEventIndex: null as number | null,
  currentMelodyEventFoundNotes: new Set<string>(),
  performancePromptResolved: false,
  performancePromptMatched: false,
  performancePromptHadAttempt: false,
  performancePromptHadWrongAttempt: false,
  performanceTimelineFeedbackKey: null as string | null,
  performanceTimelineFeedbackByEvent: {} as PerformanceTimelineFeedbackByEvent,
  performanceTimingByEvent: {} as Record<number, PerformanceTimingEventLogEntry[]>,
  performanceOnsetRejectsByEvent: {} as Record<number, PerformanceOnsetRejectEventLogEntry[]>,
  performanceCaptureTelemetryByEvent: {} as Record<number, PerformanceCaptureEventTelemetry>,
  showSessionSummaryOnStop: false,
  melodyTransposeSemitones: 0,
  melodyTransposeById: {} as Record<string, number>,
  melodyPlaybackBpmById: {} as Record<string, number>,
  melodyStringShift: 0,
  melodyStringShiftById: {} as Record<string, number>,
  melodyDemoRuntimeActive: false,
  melodyDemoRuntimePaused: false,
  melodyDemoRuntimeBaseTimeSec: 0,
  melodyDemoRuntimeAnchorStartedAtMs: null as number | null,
  melodyDemoRuntimePausedOffsetSec: 0,
  melodyStudyRangeStartIndex: 0,
  melodyStudyRangeEndIndex: 0,
  melodyStudyRangeById: {} as Record<string, { startIndex: number; endIndex: number }>,
  melodyLoopRangeEnabled: false,
  showMelodyTabTimeline: true,
  showScrollingTabPanel: true,
  melodyTimelineZoomPercent: 100,
  scrollingTabZoomPercent: 100,
  melodyTimelinePreviewIndex: null as number | null,
  melodyTimelinePreviewLabel: null as string | null,
  performancePrerollLeadInVisible: false,
  performancePrerollStartedAtMs: null as number | null,
  performancePrerollDurationMs: 0,
  performancePrerollStepIndex: null as number | null,
  performanceRuntimeStartedAtMs: null as number | null,
  performanceTransportAnimationId: 0,
  melodyTimelineViewMode: 'classic' as 'classic' | 'grid',
  melodyTimelineSelectedEventIndex: null as number | null,
  melodyTimelineSelectedNoteIndex: null as number | null,
  preferredMelodyId: null as string | null,
  melodyEditorMode: 'create' as 'create' | 'edit-custom' | 'duplicate-builtin',
  editingMelodyId: null as string | null,
  pendingSessionStopResultMessage: null as
    | { text: string; tone: 'neutral' | 'success' | 'error' }
    | null,
  // --- End mode-specific state ---
  targetFrequency: null as number | null,
  calibratedA4: DEFAULT_A4_FREQUENCY,
  isCalibrating: false,
  calibrationFrequencies: [] as number[],
  pendingTimeoutIds: new Set<number>(),
  timerId: null as number | null,
  timeLeft: 0,
  currentScore: 0,
  sessionPace: 'normal' as SessionPace,
  stats: {
    highScore: 0,
    totalAttempts: 0,
    correctAttempts: 0,
    totalTime: 0,
    noteStats: {},
  } as Stats,
  activeSessionStats: null as SessionStats | null,
  lastSessionStats: null as SessionStats | null,
  lastSessionPerformanceNoteLog: null as PerformanceSessionNoteLogSnapshot | null,
  lastSessionAnalysisBundle: null as SessionAnalysisBundle | null,
  lastSessionAnalysisAutoDownloadKey: null as string | null,
  performanceStarsByRunKey: {} as Record<string, number>,
  performanceRunCompleted: false,
  currentInstrument: instruments.guitar as IInstrument,
  currentTuningPresetKey: 'standard',
  inputSource: 'microphone' as 'microphone' | 'midi',
  uiWorkflow: 'learn-notes' as UiWorkflow,
  uiMode: 'simple' as UiMode,
  isDirectInputMode: false,
  audioInputLastErrorKind: null as 'permission' | 'device' | 'unsupported' | 'unknown' | null,
  audioInputLastErrorMessage: null as string | null,
  preferredAudioInputDeviceId: null as string | null,
  micSensitivityPreset: 'normal' as MicSensitivityPreset,
  micNoteAttackFilterPreset: 'balanced' as MicNoteAttackFilterPreset,
  micNoteHoldFilterPreset: '80ms' as MicNoteHoldFilterPreset,
  performanceMicHoldCalibrationLevel: 'off' as PerformanceMicHoldCalibrationLevel,
  micAutoNoiseFloorRms: null as number | null,
  micMonophonicAttackTrackedNote: null as string | null,
  micMonophonicAttackPeakVolume: 0,
  micMonophonicAttackLastVolume: 0,
  micMonophonicFirstDetectedAtMs: null as number | null,
  studyMelodyRepeatPromptRequiresFreshAttack: false,
  studyMelodyRepeatPromptSawSilence: false,
  micLastInputRms: 0,
  micLastMonophonicConfidence: null as number | null,
  micLastMonophonicPitchSpreadCents: null as number | null,
  micLastMonophonicDetectedAtMs: null as number | null,
  micPerformanceReadinessLastUiRefreshAtMs: 0,
  micPerformanceJudgmentCount: 0,
  micPerformanceJudgmentTotalLatencyMs: 0,
  micPerformanceJudgmentLastLatencyMs: null as number | null,
  micPerformanceJudgmentMaxLatencyMs: 0,
  micPerformanceSuggestedLatencyMs: null as number | null,
  micPerformanceLatencyCalibrationActive: false,
  micPerformanceOnsetGateStatus: 'idle' as 'idle' | 'accepted' | 'rejected',
  micPerformanceOnsetGateReason: null as string | null,
  micPerformanceOnsetGateAtMs: null as number | null,
  micPerformanceOnsetRejectedWeakAttackCount: 0,
  micPerformanceOnsetRejectedLowConfidenceCount: 0,
  micPerformanceOnsetRejectedLowVoicingCount: 0,
  micPerformanceOnsetRejectedShortHoldCount: 0,
  micPerformanceOnsetLastRejectedNote: null as string | null,
  micPerformanceOnsetLastRejectedAtMs: null as number | null,
  micPerformanceOnsetLastRejectedReasonKey: null as MicPerformanceOnsetRejectReasonKey | null,
  performanceMicLastJudgedOnsetNote: null as string | null,
    performanceMicLastJudgedOnsetAtMs: null as number | null,
    performanceMicLastUncertainOnsetNote: null as string | null,
    performanceMicLastUncertainOnsetAtMs: null as number | null,
    micPolyphonicDetectorProvider: 'spectrum' as MicPolyphonicDetectorProvider,
  lastMicPolyphonicDetectorProviderUsed: null as MicPolyphonicDetectorProvider | null,
  lastMicPolyphonicDetectorFallbackFrom: null as MicPolyphonicDetectorProvider | null,
  lastMicPolyphonicDetectorWarning: null as string | null,
  micPolyphonicDetectorTelemetryFrames: 0,
  micPolyphonicDetectorTelemetryTotalLatencyMs: 0,
  micPolyphonicDetectorTelemetryMaxLatencyMs: 0,
  micPolyphonicDetectorTelemetryLastLatencyMs: null as number | null,
  micPolyphonicDetectorTelemetryFallbackFrames: 0,
  micPolyphonicDetectorTelemetryWarningFrames: 0,
  micPolyphonicDetectorTelemetryWindowStartedAtMs: 0,
  micPolyphonicDetectorTelemetryLastUiRefreshAtMs: 0,
  preferredMidiInputDeviceId: null as string | null,
  midiAccess: null as MIDIAccess | null,
  midiInput: null as MIDIInput | null,
  isLoadingSamples: false,
  audioCache: {} as Partial<Record<IInstrument['name'], SoundfontPlayer>>, // Loaded soundfont players by instrument
};

