/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import type { SoundfontPlayer } from 'soundfont-player';
import type { Stats, Prompt, SessionStats } from './types';
import { DEFAULT_A4_FREQUENCY } from './constants';
import { IInstrument } from './instruments/instrument';
import { instruments } from './instruments';

// --- DOM ELEMENTS ---
export const dom = {
  showAllNotes: document.getElementById('showAllNotes') as HTMLInputElement,
  showStringToggles: document.getElementById('showStringToggles') as HTMLInputElement,
  instrumentSelector: document.getElementById('instrumentSelector') as HTMLSelectElement,
  inputSource: document.getElementById('inputSource') as HTMLSelectElement,
  tuningPreset: document.getElementById('tuningPreset') as HTMLSelectElement,
  difficulty: document.getElementById('difficulty') as HTMLSelectElement,
  noteNaming: document.getElementById('noteNaming') as HTMLSelectElement,
  audioInputDevice: document.getElementById('audioInputDevice') as HTMLSelectElement,
  midiInputRow: document.getElementById('midiInputRow') as HTMLElement,
  midiInputDevice: document.getElementById('midiInputDevice') as HTMLSelectElement,
  trainingMode: document.getElementById('trainingMode') as HTMLSelectElement,
  sessionGoal: document.getElementById('sessionGoal') as HTMLSelectElement,
  curriculumPreset: document.getElementById('curriculumPreset') as HTMLSelectElement,
  scaleSelectorContainer: document.getElementById('scaleSelectorContainer') as HTMLElement,
  scaleSelector: document.getElementById('scaleSelector') as HTMLSelectElement,
  chordSelectorContainer: document.getElementById('chordSelectorContainer') as HTMLElement,
  chordSelector: document.getElementById('chordSelector') as HTMLSelectElement,
  randomizeChords: document.getElementById('randomizeChords') as HTMLInputElement,
  progressionSelectorContainer: document.getElementById(
    'progressionSelectorContainer'
  ) as HTMLElement,
  progressionSelector: document.getElementById('progressionSelector') as HTMLSelectElement,
  arpeggioPatternContainer: document.getElementById('arpeggioPatternContainer') as HTMLElement,
  arpeggioPatternSelector: document.getElementById('arpeggioPatternSelector') as HTMLSelectElement,
  startFret: document.getElementById('startFret') as HTMLInputElement,
  endFret: document.getElementById('endFret') as HTMLInputElement,
  metronomeEnabled: document.getElementById('metronomeEnabled') as HTMLInputElement,
  metronomeBpm: document.getElementById('metronomeBpm') as HTMLInputElement,
  rhythmTimingWindow: document.getElementById('rhythmTimingWindow') as HTMLSelectElement,
  metronomePulse: document.getElementById('metronomePulse') as HTMLElement,
  metronomeBeatLabel: document.getElementById('metronomeBeatLabel') as HTMLElement,
  profileSelector: document.getElementById('profileSelector') as HTMLSelectElement,
  saveAsProfileBtn: document.getElementById('saveAsProfileBtn') as HTMLButtonElement,
  updateProfileBtn: document.getElementById('updateProfileBtn') as HTMLButtonElement,
  deleteProfileBtn: document.getElementById('deleteProfileBtn') as HTMLButtonElement,
  hintBtn: document.getElementById('hintBtn') as HTMLButtonElement,
  settingsBtn: document.getElementById('settingsBtn') as HTMLButtonElement,
  practiceSetupToggleBtn: document.getElementById('practiceSetupToggleBtn') as HTMLButtonElement,
  practiceSetupChevron: document.getElementById('practiceSetupChevron') as HTMLElement,
  practiceSetupPanel: document.getElementById('practiceSetupPanel') as HTMLElement,
  practiceSetupSummary: document.getElementById('practiceSetupSummary') as HTMLElement,
  sessionToolsToggleBtn: document.getElementById('sessionToolsToggleBtn') as HTMLButtonElement,
  sessionToolsChevron: document.getElementById('sessionToolsChevron') as HTMLElement,
  sessionToolsPanel: document.getElementById('sessionToolsPanel') as HTMLElement,
  sessionToolsPrimaryControls: document.getElementById('sessionToolsPrimaryControls') as HTMLElement,
  sessionToolsShowAllNotesRow: document.getElementById('sessionToolsShowAllNotesRow') as HTMLElement,
  sessionToolsActiveStringsSection: document.getElementById('sessionToolsActiveStringsSection') as HTMLElement,
  sessionToolsStringSelector: document.getElementById('sessionToolsStringSelector') as HTMLElement,
  metronomeQuickControls: document.getElementById('metronomeQuickControls') as HTMLElement,
  curriculumPresetInfo: document.getElementById('curriculumPresetInfo') as HTMLElement,
  tuningPresetInfo: document.getElementById('tuningPresetInfo') as HTMLElement,
  audioInputInfo: document.getElementById('audioInputInfo') as HTMLElement,
  midiInputInfo: document.getElementById('midiInputInfo') as HTMLElement,
  modeHelpText: document.getElementById('modeHelpText') as HTMLElement,
  fretboard: document.querySelector('.fretboard') as HTMLElement,
  fretboardSvg: document.getElementById('fretboardSvg') as SVGSVGElement,
  infoSlot1: document.getElementById('infoSlot1')!,
  infoSlot2: document.getElementById('infoSlot2')!,
  infoSlot3: document.getElementById('infoSlot3')!,
  timedInfo: document.getElementById('timedInfo') as HTMLElement,
  timer: document.getElementById('timer') as HTMLElement,
  score: document.getElementById('score') as HTMLElement,
  prompt: document.getElementById('prompt')!,
  playSoundBtn: document.getElementById('playSoundBtn') as HTMLButtonElement,
  stringSelector: document.getElementById('fretboard-string-selector') as HTMLElement,
  sessionToggleBtn: document.getElementById('sessionToggleBtn') as HTMLButtonElement,
  startBtn: document.getElementById('startBtn') as HTMLButtonElement,
  stopBtn: document.getElementById('stopBtn') as HTMLButtonElement,
  result: document.getElementById('result')!,
  sessionGoalProgress: document.getElementById('sessionGoalProgress') as HTMLElement,
  tunerDisplay: document.getElementById('tunerDisplay') as HTMLElement,
  tunerNeedle: document.getElementById('tunerNeedle') as HTMLElement,
  tunerCents: document.getElementById('tunerCents') as HTMLElement,
  volumeBar: document.getElementById('volumeBar')!,
  statusBar: document.getElementById('statusBar')!,
  inputStatusBar: document.getElementById('inputStatusBar') as HTMLElement,
  loadingOverlay: document.getElementById('loadingOverlay') as HTMLElement,
  loadingMessage: document.getElementById('loadingMessage') as HTMLElement,
  settingsModal: document.getElementById('settingsModal') as HTMLElement,
  closeSettingsBtn: document.getElementById('closeSettingsBtn') as HTMLButtonElement,
  openCalibrateBtn: document.getElementById('openCalibrateBtn') as HTMLButtonElement,
  openStatsBtn: document.getElementById('openStatsBtn') as HTMLButtonElement,
  openGuideBtn: document.getElementById('openGuideBtn') as HTMLButtonElement,
  openLinksBtn: document.getElementById('openLinksBtn') as HTMLButtonElement,
  calibrationModal: document.getElementById('calibrationModal') as HTMLElement,
  calibrationProgress: document.getElementById('calibrationProgress') as HTMLElement,
  calibrationStatus: document.getElementById('calibrationStatus') as HTMLElement,
  cancelCalibrationBtn: document.getElementById('cancelCalibrationBtn') as HTMLButtonElement,
  statsModal: document.getElementById('statsModal') as HTMLElement,
  closeStatsBtn: document.getElementById('closeStatsBtn') as HTMLButtonElement,
  statsHighScore: document.getElementById('statsHighScore') as HTMLElement,
  statsAccuracy: document.getElementById('statsAccuracy') as HTMLElement,
  statsAvgTime: document.getElementById('statsAvgTime') as HTMLElement,
  statsProblemNotes: document.getElementById('statsProblemNotes') as HTMLElement,
  statsLastSessionSection: document.getElementById('statsLastSessionSection') as HTMLElement,
  statsLastSessionMode: document.getElementById('statsLastSessionMode') as HTMLElement,
  statsLastSessionDuration: document.getElementById('statsLastSessionDuration') as HTMLElement,
  statsLastSessionAttempts: document.getElementById('statsLastSessionAttempts') as HTMLElement,
  statsLastSessionAccuracy: document.getElementById('statsLastSessionAccuracy') as HTMLElement,
  statsLastSessionAvgTime: document.getElementById('statsLastSessionAvgTime') as HTMLElement,
  statsLastSessionBestStreak: document.getElementById('statsLastSessionBestStreak') as HTMLElement,
  statsLastSessionCoachTip: document.getElementById('statsLastSessionCoachTip') as HTMLElement,
  statsLastSessionWeakSpots: document.getElementById('statsLastSessionWeakSpots') as HTMLElement,
  statsLastSessionRhythmSummary: document.getElementById('statsLastSessionRhythmSummary') as HTMLElement,
  statsRhythmOnBeat: document.getElementById('statsRhythmOnBeat') as HTMLElement,
  statsRhythmEarly: document.getElementById('statsRhythmEarly') as HTMLElement,
  statsRhythmLate: document.getElementById('statsRhythmLate') as HTMLElement,
  statsRhythmAvgOffset: document.getElementById('statsRhythmAvgOffset') as HTMLElement,
  statsRhythmBestOffset: document.getElementById('statsRhythmBestOffset') as HTMLElement,
  statsLastSessionHeatmap: document.getElementById('statsLastSessionHeatmap') as HTMLElement,
  repeatLastSessionBtn: document.getElementById('repeatLastSessionBtn') as HTMLButtonElement,
  practiceWeakSpotsBtn: document.getElementById('practiceWeakSpotsBtn') as HTMLButtonElement,
  resetStatsBtn: document.getElementById('resetStatsBtn') as HTMLButtonElement,
  guideModal: document.getElementById('guideModal') as HTMLElement,
  closeGuideBtn: document.getElementById('closeGuideBtn') as HTMLButtonElement,
  linksModal: document.getElementById('linksModal') as HTMLElement,
  closeLinksBtn: document.getElementById('closeLinksBtn') as HTMLButtonElement,
  // Profile Name Modal
  profileNameModal: document.getElementById('profileNameModal') as HTMLElement,
  profileNameInput: document.getElementById('profileNameInput') as HTMLInputElement,
  confirmSaveProfileBtn: document.getElementById('confirmSaveProfileBtn') as HTMLButtonElement,
  cancelSaveProfileBtn: document.getElementById('cancelSaveProfileBtn') as HTMLButtonElement,
};

// --- APPLICATION STATE ---
export const state = {
  audioContext: null as AudioContext | null,
  analyser: null as AnalyserNode | null,
  microphone: null as MediaStreamAudioSourceNode | null,
  mediaStream: null as MediaStream | null,
  activeAudioInputDeviceId: null as string | null,
  dataArray: null as Float32Array | null, // For monophonic (time domain)
  frequencyDataArray: null as Float32Array | null, // For polyphonic (frequency domain)
  isListening: false,
  animationId: 0,
  currentPrompt: null as Prompt | null,
  liveDetectedNote: null as string | null,
  liveDetectedString: null as string | null,
  previousNote: null as string | null, // To avoid consecutive identical prompts
  startTime: 0,
  stableNoteCounter: 0,
  lastNote: null as string | null,
  lastDetectedChord: '',
  stableChordCounter: 0,
  consecutiveSilence: 0,
  lastPitches: [] as number[],
  rhythmLastJudgedBeatAtMs: null as number | null,
  showingAllNotes: false,
  cooldown: false,
  // --- Mode-specific state (managed by mode classes) ---
  scaleNotes: [] as { note: string; string: string }[],
  currentScaleIndex: 0,
  currentProgression: [] as string[],
  currentProgressionIndex: 0,
  currentArpeggioIndex: 0,
  // --- End mode-specific state ---
  targetFrequency: null as number | null,
  calibratedA4: DEFAULT_A4_FREQUENCY,
  isCalibrating: false,
  calibrationFrequencies: [] as number[],
  pendingTimeoutIds: new Set<number>(),
  timerId: null as number | null,
  timeLeft: 0,
  currentScore: 0,
  stats: {
    highScore: 0,
    totalAttempts: 0,
    correctAttempts: 0,
    totalTime: 0,
    noteStats: {},
  } as Stats,
  activeSessionStats: null as SessionStats | null,
  lastSessionStats: null as SessionStats | null,
  currentInstrument: instruments.guitar as IInstrument,
  currentTuningPresetKey: 'standard',
  inputSource: 'microphone' as 'microphone' | 'midi',
  preferredAudioInputDeviceId: null as string | null,
  preferredMidiInputDeviceId: null as string | null,
  midiAccess: null as MIDIAccess | null,
  midiInput: null as MIDIInput | null,
  isLoadingSamples: false,
  audioCache: {} as Partial<Record<IInstrument['name'], SoundfontPlayer>>, // Loaded soundfont players by instrument
};
