/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import type { SoundfontPlayer } from 'soundfont-player';
import type { Stats, Prompt, SessionStats } from './types';
import { DEFAULT_A4_FREQUENCY } from './constants';
import { IInstrument } from './instruments/instrument';
import { instruments } from './instruments';
import type { SessionPace } from './session-pace';
import type { MicSensitivityPreset } from './mic-input-sensitivity';
import type { MicNoteAttackFilterPreset } from './mic-note-attack-filter';
import type { MicNoteHoldFilterPreset } from './mic-note-hold-filter';
import type { MicPolyphonicDetectorProvider } from './mic-polyphonic-detector';

function requireElementById<T extends Element>(id: string): T {
  const element = document.getElementById(id);
  if (!element) {
    throw new Error(`Missing required DOM element: #${id}`);
  }
  return element as T;
}

function requireQuerySelector<T extends Element>(selector: string): T {
  const element = document.querySelector(selector);
  if (!element) {
    throw new Error(`Missing required DOM element: ${selector}`);
  }
  return element as T;
}

// --- DOM ELEMENTS ---
export const dom = {
  showAllNotes: requireElementById<HTMLInputElement>('showAllNotes'),
  showStringToggles: requireElementById<HTMLInputElement>('showStringToggles'),
  autoPlayPromptSound: requireElementById<HTMLInputElement>('autoPlayPromptSound'),
  instrumentSelector: requireElementById<HTMLSelectElement>('instrumentSelector'),
  inputSource: requireElementById<HTMLSelectElement>('inputSource'),
  tuningPreset: requireElementById<HTMLSelectElement>('tuningPreset'),
  difficulty: requireElementById<HTMLSelectElement>('difficulty'),
  noteNaming: requireElementById<HTMLSelectElement>('noteNaming'),
  timelineViewMode: requireElementById<HTMLSelectElement>('timelineViewMode'),
  showTimelineSteps: requireElementById<HTMLInputElement>('showTimelineSteps'),
  showTimelineDetails: requireElementById<HTMLInputElement>('showTimelineDetails'),
  audioInputRow: requireElementById<HTMLElement>('audioInputRow'),
  audioInputDevice: requireElementById<HTMLSelectElement>('audioInputDevice'),
  micSensitivityRow: requireElementById<HTMLElement>('micSensitivityRow'),
  micSensitivityPreset: requireElementById<HTMLSelectElement>('micSensitivityPreset'),
  micAttackFilterRow: requireElementById<HTMLElement>('micAttackFilterRow'),
  micNoteAttackFilter: requireElementById<HTMLSelectElement>('micNoteAttackFilter'),
  micHoldFilterRow: requireElementById<HTMLElement>('micHoldFilterRow'),
  micNoteHoldFilter: requireElementById<HTMLSelectElement>('micNoteHoldFilter'),
  micPolyphonicDetectorRow: requireElementById<HTMLElement>('micPolyphonicDetectorRow'),
  micPolyphonicDetectorProvider: requireElementById<HTMLSelectElement>('micPolyphonicDetectorProvider'),
  micNoiseCalibrationRow: requireElementById<HTMLElement>('micNoiseCalibrationRow'),
  calibrateNoiseFloorBtn: requireElementById<HTMLButtonElement>('calibrateNoiseFloorBtn'),
  midiInputRow: requireElementById<HTMLElement>('midiInputRow'),
  midiInputDevice: requireElementById<HTMLSelectElement>('midiInputDevice'),
  trainingMode: requireElementById<HTMLSelectElement>('trainingMode'),
  trainingModeField: requireElementById<HTMLElement>('trainingModeField'),
  sessionGoal: requireElementById<HTMLSelectElement>('sessionGoal'),
  sessionPace: requireElementById<HTMLSelectElement>('sessionPace'),
  curriculumPreset: requireElementById<HTMLSelectElement>('curriculumPreset'),
  scaleSelectorContainer: requireElementById<HTMLElement>('scaleSelectorContainer'),
  melodySelectorContainer: requireElementById<HTMLElement>('melodySelectorContainer'),
  melodySelector: requireElementById<HTMLSelectElement>('melodySelector'),
  melodyTranspose: requireElementById<HTMLInputElement>('melodyTranspose'),
  melodyTransposeValue: requireElementById<HTMLElement>('melodyTransposeValue'),
  melodyTransposeDownBtn: requireElementById<HTMLButtonElement>('melodyTransposeDownBtn'),
  melodyTransposeUpBtn: requireElementById<HTMLButtonElement>('melodyTransposeUpBtn'),
  melodyTransposeResetBtn: requireElementById<HTMLButtonElement>('melodyTransposeResetBtn'),
  melodyStringShift: requireElementById<HTMLInputElement>('melodyStringShift'),
  melodyStringShiftValue: requireElementById<HTMLElement>('melodyStringShiftValue'),
  melodyStringShiftDownBtn: requireElementById<HTMLButtonElement>('melodyStringShiftDownBtn'),
  melodyStringShiftUpBtn: requireElementById<HTMLButtonElement>('melodyStringShiftUpBtn'),
  melodyStringShiftResetBtn: requireElementById<HTMLButtonElement>('melodyStringShiftResetBtn'),
  melodyTransposeBatchCustomBtn: requireElementById<HTMLButtonElement>('melodyTransposeBatchCustomBtn'),
  melodyStudyStart: requireElementById<HTMLInputElement>('melodyStudyStart'),
  melodyStudyEnd: requireElementById<HTMLInputElement>('melodyStudyEnd'),
  melodyStudyValue: requireElementById<HTMLElement>('melodyStudyValue'),
  melodyStudyResetBtn: requireElementById<HTMLButtonElement>('melodyStudyResetBtn'),
  melodyLoopRange: requireElementById<HTMLInputElement>('melodyLoopRange'),
  melodyShowNote: requireElementById<HTMLInputElement>('melodyShowNote'),
  melodyPlaybackControls: requireElementById<HTMLElement>('melodyPlaybackControls'),
  melodyDemoQuickControls: requireElementById<HTMLElement>('melodyDemoQuickControls'),
  openMelodyImportBtn: requireElementById<HTMLButtonElement>('openMelodyImportBtn'),
  editMelodyBtn: requireElementById<HTMLButtonElement>('editMelodyBtn'),
  exportMelodyMidiBtn: requireElementById<HTMLButtonElement>('exportMelodyMidiBtn'),
  exportPracticeMelodyMidiBtn: requireElementById<HTMLButtonElement>('exportPracticeMelodyMidiBtn'),
  melodyDemoBtn: requireElementById<HTMLButtonElement>('melodyDemoBtn'),
  melodyPauseDemoBtn: requireElementById<HTMLButtonElement>('melodyPauseDemoBtn'),
  melodyStepBackBtn: requireElementById<HTMLButtonElement>('melodyStepBackBtn'),
  melodyStepForwardBtn: requireElementById<HTMLButtonElement>('melodyStepForwardBtn'),
  melodyDemoBpm: requireElementById<HTMLInputElement>('melodyDemoBpm'),
  melodyDemoBpmValue: requireElementById<HTMLElement>('melodyDemoBpmValue'),
  melodyTabTimelinePanel: requireElementById<HTMLElement>('melodyTabTimelinePanel'),
  melodyTabTimelineMinimap: requireElementById<HTMLElement>('melodyTabTimelineMinimap'),
  melodyTabTimelineViewport: requireElementById<HTMLElement>('melodyTabTimelineViewport'),
  melodyTabTimelineMeta: requireElementById<HTMLElement>('melodyTabTimelineMeta'),
  melodyTabTimelineGrid: requireElementById<HTMLElement>('melodyTabTimelineGrid'),
  melodyTimelineEditorPanel: requireElementById<HTMLElement>('melodyTimelineEditorPanel'),
  melodyTimelineEditorStatus: requireElementById<HTMLElement>('melodyTimelineEditorStatus'),
  melodyTimelineEditorSelection: requireElementById<HTMLElement>('melodyTimelineEditorSelection'),
  melodyTimelineEditorShortcutHint: requireElementById<HTMLElement>('melodyTimelineEditorShortcutHint'),
  melodyTimelineEditorDuration: requireElementById<HTMLElement>('melodyTimelineEditorDuration'),
  melodyTimelineEditorDurationDownBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorDurationDownBtn'),
  melodyTimelineEditorDurationUpBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorDurationUpBtn'),
  melodyTimelineEditorNoteSelector: requireElementById<HTMLElement>('melodyTimelineEditorNoteSelector'),
  melodyTimelineEditorString: requireElementById<HTMLSelectElement>('melodyTimelineEditorString'),
  melodyTimelineEditorFret: requireElementById<HTMLInputElement>('melodyTimelineEditorFret'),
  melodyTimelineEditorAddBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorAddBtn'),
  melodyTimelineEditorAddEventBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorAddEventBtn'),
  melodyTimelineEditorDuplicateEventBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorDuplicateEventBtn'),
  melodyTimelineEditorMoveEventLeftBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorMoveEventLeftBtn'),
  melodyTimelineEditorMoveEventRightBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorMoveEventRightBtn'),
  melodyTimelineEditorSplitEventBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorSplitEventBtn'),
  melodyTimelineEditorMergeEventBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorMergeEventBtn'),
  melodyTimelineEditorDeleteEventBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorDeleteEventBtn'),
  melodyTimelineEditorDeleteBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorDeleteBtn'),
  melodyTimelineEditorUndoBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorUndoBtn'),
  melodyTimelineEditorRedoBtn: requireElementById<HTMLButtonElement>('melodyTimelineEditorRedoBtn'),
  melodyNameInput: requireElementById<HTMLInputElement>('melodyNameInput'),
  melodyAsciiTabInput: requireElementById<HTMLTextAreaElement>('melodyAsciiTabInput'),
  melodyGpFileInput: requireElementById<HTMLInputElement>('melodyGpFileInput'),
  melodyMidiFileInput: requireElementById<HTMLInputElement>('melodyMidiFileInput'),
  melodyGpTrackImportPanel: requireElementById<HTMLElement>('melodyGpTrackImportPanel'),
  melodyGpTrackSelector: requireElementById<HTMLSelectElement>('melodyGpTrackSelector'),
  melodyGpTrackInfo: requireElementById<HTMLElement>('melodyGpTrackInfo'),
  saveMelodyGpTrackBtn: requireElementById<HTMLButtonElement>('saveMelodyGpTrackBtn'),
  melodyMidiTrackImportPanel: requireElementById<HTMLElement>('melodyMidiTrackImportPanel'),
  melodyMidiTrackSelector: requireElementById<HTMLSelectElement>('melodyMidiTrackSelector'),
  melodyMidiQuantize: requireElementById<HTMLSelectElement>('melodyMidiQuantize'),
  melodyMidiTrackInfo: requireElementById<HTMLElement>('melodyMidiTrackInfo'),
  saveMelodyMidiTrackBtn: requireElementById<HTMLButtonElement>('saveMelodyMidiTrackBtn'),
  melodyImportTitle: requireElementById<HTMLElement>('melodyImportTitle'),
  melodyImportHelpText: requireElementById<HTMLElement>('melodyImportHelpText'),
  melodyPreviewStatus: requireElementById<HTMLElement>('melodyPreviewStatus'),
  melodyPreviewSummary: requireElementById<HTMLElement>('melodyPreviewSummary'),
  melodyPreviewList: requireElementById<HTMLElement>('melodyPreviewList'),
  melodyEventEditorPanel: requireElementById<HTMLElement>('melodyEventEditorPanel'),
  melodyEventEditorSelection: requireElementById<HTMLElement>('melodyEventEditorSelection'),
  melodyEventEditorNoteSelector: requireElementById<HTMLElement>('melodyEventEditorNoteSelector'),
  melodyEventEditorString: requireElementById<HTMLSelectElement>('melodyEventEditorString'),
  melodyEventEditorFret: requireElementById<HTMLInputElement>('melodyEventEditorFret'),
  melodyEventEditorAddBtn: requireElementById<HTMLButtonElement>('melodyEventEditorAddBtn'),
  melodyEventEditorDeleteBtn: requireElementById<HTMLButtonElement>('melodyEventEditorDeleteBtn'),
  melodyEventEditorUndoBtn: requireElementById<HTMLButtonElement>('melodyEventEditorUndoBtn'),
  melodyEventEditorRedoBtn: requireElementById<HTMLButtonElement>('melodyEventEditorRedoBtn'),
  importMelodyGpBtn: requireElementById<HTMLButtonElement>('importMelodyGpBtn'),
  importMelodyMidiBtn: requireElementById<HTMLButtonElement>('importMelodyMidiBtn'),
  importMelodyBtn: requireElementById<HTMLButtonElement>('importMelodyBtn'),
  deleteMelodyBtn: requireElementById<HTMLButtonElement>('deleteMelodyBtn'),
  scaleSelector: requireElementById<HTMLSelectElement>('scaleSelector'),
  chordSelectorContainer: requireElementById<HTMLElement>('chordSelectorContainer'),
  chordSelector: requireElementById<HTMLSelectElement>('chordSelector'),
  randomizeChords: requireElementById<HTMLInputElement>('randomizeChords'),
  progressionSelectorContainer: requireElementById<HTMLElement>('progressionSelectorContainer'),
  progressionSelector: requireElementById<HTMLSelectElement>('progressionSelector'),
  arpeggioPatternContainer: requireElementById<HTMLElement>('arpeggioPatternContainer'),
  arpeggioPatternSelector: requireElementById<HTMLSelectElement>('arpeggioPatternSelector'),
  startFret: requireElementById<HTMLInputElement>('startFret'),
  endFret: requireElementById<HTMLInputElement>('endFret'),
  metronomeEnabled: requireElementById<HTMLInputElement>('metronomeEnabled'),
  metronomeBpm: requireElementById<HTMLInputElement>('metronomeBpm'),
  metronomeBpmValue: requireElementById<HTMLElement>('metronomeBpmValue'),
  rhythmTimingWindow: requireElementById<HTMLSelectElement>('rhythmTimingWindow'),
  metronomePulse: requireElementById<HTMLElement>('metronomePulse'),
  metronomeBeatLabel: requireElementById<HTMLElement>('metronomeBeatLabel'),
  profileSelector: requireElementById<HTMLSelectElement>('profileSelector'),
  saveAsProfileBtn: requireElementById<HTMLButtonElement>('saveAsProfileBtn'),
  updateProfileBtn: requireElementById<HTMLButtonElement>('updateProfileBtn'),
  deleteProfileBtn: requireElementById<HTMLButtonElement>('deleteProfileBtn'),
  hintBtn: requireElementById<HTMLButtonElement>('hintBtn'),
  settingsBtn: requireElementById<HTMLButtonElement>('settingsBtn'),
  practiceSetupToggleBtn: requireElementById<HTMLButtonElement>('practiceSetupToggleBtn'),
  practiceSetupChevron: requireElementById<HTMLElement>('practiceSetupChevron'),
  practiceSetupPanel: requireElementById<HTMLElement>('practiceSetupPanel'),
  practiceSetupSummary: requireElementById<HTMLElement>('practiceSetupSummary'),
  melodySetupToggleBtn: requireElementById<HTMLButtonElement>('melodySetupToggleBtn'),
  melodySetupChevron: requireElementById<HTMLElement>('melodySetupChevron'),
  melodySetupPanel: requireElementById<HTMLElement>('melodySetupPanel'),
  melodySetupSummary: requireElementById<HTMLElement>('melodySetupSummary'),
  sessionToolsToggleBtn: requireElementById<HTMLButtonElement>('sessionToolsToggleBtn'),
  sessionToolsChevron: requireElementById<HTMLElement>('sessionToolsChevron'),
  sessionToolsPanel: requireElementById<HTMLElement>('sessionToolsPanel'),
  sessionToolsSummary: requireElementById<HTMLElement>('sessionToolsSummary'),
  sessionToolsPrimaryControls: requireElementById<HTMLElement>('sessionToolsPrimaryControls'),
  sessionToolsShowAllNotesRow: requireElementById<HTMLElement>('sessionToolsShowAllNotesRow'),
  sessionToolsActiveStringsSection: requireElementById<HTMLElement>('sessionToolsActiveStringsSection'),
  sessionToolsStringSelector: requireElementById<HTMLElement>('sessionToolsStringSelector'),
  metronomeQuickControls: requireElementById<HTMLElement>('metronomeQuickControls'),
  curriculumPresetInfo: requireElementById<HTMLElement>('curriculumPresetInfo'),
  tuningPresetInfo: requireElementById<HTMLElement>('tuningPresetInfo'),
  audioInputInfo: requireElementById<HTMLElement>('audioInputInfo'),
  micNoiseGateInfo: requireElementById<HTMLElement>('micNoiseGateInfo'),
  midiInputInfo: requireElementById<HTMLElement>('midiInputInfo'),
  midiConnectionStatus: requireElementById<HTMLElement>('midiConnectionStatus'),
  modeHelpText: requireElementById<HTMLElement>('modeHelpText'),
  fretboard: requireQuerySelector<HTMLElement>('.fretboard'),
  fretboardSvg: requireElementById<SVGSVGElement>('fretboardSvg'),
  infoSlot1: requireElementById<HTMLElement>('infoSlot1'),
  infoSlot2: requireElementById<HTMLElement>('infoSlot2'),
  infoSlot3: requireElementById<HTMLElement>('infoSlot3'),
  timedInfo: requireElementById<HTMLElement>('timedInfo'),
  timer: requireElementById<HTMLElement>('timer'),
  score: requireElementById<HTMLElement>('score'),
  prompt: requireElementById<HTMLElement>('prompt'),
  playSoundBtn: requireElementById<HTMLButtonElement>('playSoundBtn'),
  stringSelector: requireElementById<HTMLElement>('fretboard-string-selector'),
  sessionToggleBtn: requireElementById<HTMLButtonElement>('sessionToggleBtn'),
  startBtn: requireElementById<HTMLButtonElement>('startBtn'),
  stopBtn: requireElementById<HTMLButtonElement>('stopBtn'),
  result: requireElementById<HTMLElement>('result'),
  sessionInlineFeedback: requireElementById<HTMLElement>('sessionInlineFeedback'),
  sessionInlineDivider: requireElementById<HTMLElement>('sessionInlineDivider'),
  sessionGoalProgress: requireElementById<HTMLElement>('sessionGoalProgress'),
  volumeSection: requireElementById<HTMLElement>('volumeSection'),
  tunerSection: requireElementById<HTMLElement>('tunerSection'),
  tunerDisplay: requireElementById<HTMLElement>('tunerDisplay'),
  tunerNeedle: requireElementById<HTMLElement>('tunerNeedle'),
  tunerCents: requireElementById<HTMLElement>('tunerCents'),
  volumeBar: requireElementById<HTMLElement>('volumeBar'),
  statusBar: requireElementById<HTMLElement>('statusBar'),
  inputStatusBar: requireElementById<HTMLElement>('inputStatusBar'),
  loadingOverlay: requireElementById<HTMLElement>('loadingOverlay'),
  loadingMessage: requireElementById<HTMLElement>('loadingMessage'),
  settingsModal: requireElementById<HTMLElement>('settingsModal'),
  closeSettingsBtn: requireElementById<HTMLButtonElement>('closeSettingsBtn'),
  openCalibrateBtn: requireElementById<HTMLButtonElement>('openCalibrateBtn'),
  openStatsBtn: requireElementById<HTMLButtonElement>('openStatsBtn'),
  openGuideBtn: requireElementById<HTMLButtonElement>('openGuideBtn'),
  openLinksBtn: requireElementById<HTMLButtonElement>('openLinksBtn'),
  calibrationModal: requireElementById<HTMLElement>('calibrationModal'),
  calibrationProgress: requireElementById<HTMLElement>('calibrationProgress'),
  calibrationStatus: requireElementById<HTMLElement>('calibrationStatus'),
  cancelCalibrationBtn: requireElementById<HTMLButtonElement>('cancelCalibrationBtn'),
  statsModal: requireElementById<HTMLElement>('statsModal'),
  closeStatsBtn: requireElementById<HTMLButtonElement>('closeStatsBtn'),
  statsHighScore: requireElementById<HTMLElement>('statsHighScore'),
  statsAccuracy: requireElementById<HTMLElement>('statsAccuracy'),
  statsAvgTime: requireElementById<HTMLElement>('statsAvgTime'),
  statsProblemNotes: requireElementById<HTMLElement>('statsProblemNotes'),
  statsLastSessionSection: requireElementById<HTMLElement>('statsLastSessionSection'),
  statsLastSessionMode: requireElementById<HTMLElement>('statsLastSessionMode'),
  statsLastSessionInput: requireElementById<HTMLElement>('statsLastSessionInput'),
  statsLastSessionDuration: requireElementById<HTMLElement>('statsLastSessionDuration'),
  statsLastSessionAttempts: requireElementById<HTMLElement>('statsLastSessionAttempts'),
  statsLastSessionAccuracy: requireElementById<HTMLElement>('statsLastSessionAccuracy'),
  statsLastSessionAvgTime: requireElementById<HTMLElement>('statsLastSessionAvgTime'),
  statsLastSessionBestStreak: requireElementById<HTMLElement>('statsLastSessionBestStreak'),
  statsLastSessionCoachTip: requireElementById<HTMLElement>('statsLastSessionCoachTip'),
  statsLastSessionWeakSpots: requireElementById<HTMLElement>('statsLastSessionWeakSpots'),
  statsLastSessionRhythmSummary: requireElementById<HTMLElement>('statsLastSessionRhythmSummary'),
  statsRhythmOnBeat: requireElementById<HTMLElement>('statsRhythmOnBeat'),
  statsRhythmEarly: requireElementById<HTMLElement>('statsRhythmEarly'),
  statsRhythmLate: requireElementById<HTMLElement>('statsRhythmLate'),
  statsRhythmAvgOffset: requireElementById<HTMLElement>('statsRhythmAvgOffset'),
  statsRhythmBestOffset: requireElementById<HTMLElement>('statsRhythmBestOffset'),
  statsLastSessionHeatmap: requireElementById<HTMLElement>('statsLastSessionHeatmap'),
  repeatLastSessionBtn: requireElementById<HTMLButtonElement>('repeatLastSessionBtn'),
  practiceWeakSpotsBtn: requireElementById<HTMLButtonElement>('practiceWeakSpotsBtn'),
  resetStatsBtn: requireElementById<HTMLButtonElement>('resetStatsBtn'),
  guideModal: requireElementById<HTMLElement>('guideModal'),
  closeGuideBtn: requireElementById<HTMLButtonElement>('closeGuideBtn'),
  linksModal: requireElementById<HTMLElement>('linksModal'),
  closeLinksBtn: requireElementById<HTMLButtonElement>('closeLinksBtn'),
  // Profile Name Modal
  profileNameModal: requireElementById<HTMLElement>('profileNameModal'),
  profileNameInput: requireElementById<HTMLInputElement>('profileNameInput'),
  confirmSaveProfileBtn: requireElementById<HTMLButtonElement>('confirmSaveProfileBtn'),
  cancelSaveProfileBtn: requireElementById<HTMLButtonElement>('cancelSaveProfileBtn'),
  melodyImportModal: requireElementById<HTMLElement>('melodyImportModal'),
  closeMelodyImportBtn: requireElementById<HTMLButtonElement>('closeMelodyImportBtn'),
  cancelMelodyImportBtn: requireElementById<HTMLButtonElement>('cancelMelodyImportBtn'),
  confirmModal: requireElementById<HTMLElement>('confirmModal'),
  confirmCloseBtn: requireElementById<HTMLButtonElement>('confirmCloseBtn'),
  confirmTitle: requireElementById<HTMLElement>('confirmTitle'),
  confirmMessage: requireElementById<HTMLElement>('confirmMessage'),
  confirmCancelBtn: requireElementById<HTMLButtonElement>('confirmCancelBtn'),
  confirmOkBtn: requireElementById<HTMLButtonElement>('confirmOkBtn'),
};

// --- APPLICATION STATE ---
export const state = {
  audioContext: null as AudioContext | null,
  analyser: null as AnalyserNode | null,
  microphone: null as MediaStreamAudioSourceNode | null,
  mediaStream: null as MediaStream | null,
  activeAudioInputDeviceId: null as string | null,
  dataArray: null as Float32Array | null, // For monophonic (time domain)
  frequencyDataArray: null as Float32Array | null, // For polyphonic (frequency domain)
  isListening: false,
  animationId: 0,
  currentPrompt: null as Prompt | null,
  liveDetectedNote: null as string | null,
  liveDetectedString: null as string | null,
  wrongDetectedNote: null as string | null,
  wrongDetectedString: null as string | null,
  wrongDetectedFret: null as number | null,
  previousNote: null as string | null, // To avoid consecutive identical prompts
  startTime: 0,
  stableNoteCounter: 0,
  lastNote: null as string | null,
  lastDetectedChord: '',
  stableChordCounter: 0,
  consecutiveSilence: 0,
  lastPitches: [] as number[],
  rhythmLastJudgedBeatAtMs: null as number | null,
  showingAllNotes: false,
  autoPlayPromptSound: true,
  showMelodyTimelineSteps: false,
  showMelodyTimelineDetails: false,
  cooldown: false,
  ignorePromptAudioUntilMs: 0,
  // --- Mode-specific state (managed by mode classes) ---
  scaleNotes: [] as { note: string; string: string }[],
  currentScaleIndex: 0,
  currentProgression: [] as string[],
  currentProgressionIndex: 0,
  currentArpeggioIndex: 0,
  currentMelodyId: null as string | null,
  currentMelodyEventIndex: 0,
  currentMelodyEventFoundNotes: new Set<string>(),
  performancePromptResolved: false,
  performancePromptMatched: false,
  melodyTransposeSemitones: 0,
  melodyTransposeById: {} as Record<string, number>,
  melodyStringShift: 0,
  melodyStringShiftById: {} as Record<string, number>,
  melodyStudyRangeStartIndex: 0,
  melodyStudyRangeEndIndex: 0,
  melodyStudyRangeById: {} as Record<string, { startIndex: number; endIndex: number }>,
  melodyLoopRangeEnabled: false,
  melodyTimelinePreviewIndex: null as number | null,
  melodyTimelinePreviewLabel: null as string | null,
  melodyTimelineViewMode: 'classic' as 'classic' | 'grid',
  melodyTimelineSelectedEventIndex: null as number | null,
  melodyTimelineSelectedNoteIndex: null as number | null,
  preferredMelodyId: null as string | null,
  melodyEditorMode: 'create' as 'create' | 'edit-custom' | 'duplicate-builtin',
  editingMelodyId: null as string | null,
  pendingSessionStopResultMessage: null as
    | { text: string; tone: 'neutral' | 'success' | 'error' }
    | null,
  // --- End mode-specific state ---
  targetFrequency: null as number | null,
  calibratedA4: DEFAULT_A4_FREQUENCY,
  isCalibrating: false,
  calibrationFrequencies: [] as number[],
  pendingTimeoutIds: new Set<number>(),
  timerId: null as number | null,
  timeLeft: 0,
  currentScore: 0,
  sessionPace: 'normal' as SessionPace,
  stats: {
    highScore: 0,
    totalAttempts: 0,
    correctAttempts: 0,
    totalTime: 0,
    noteStats: {},
  } as Stats,
  activeSessionStats: null as SessionStats | null,
  lastSessionStats: null as SessionStats | null,
  currentInstrument: instruments.guitar as IInstrument,
  currentTuningPresetKey: 'standard',
  inputSource: 'microphone' as 'microphone' | 'midi',
  preferredAudioInputDeviceId: null as string | null,
  micSensitivityPreset: 'normal' as MicSensitivityPreset,
  micNoteAttackFilterPreset: 'balanced' as MicNoteAttackFilterPreset,
  micNoteHoldFilterPreset: '80ms' as MicNoteHoldFilterPreset,
  micAutoNoiseFloorRms: null as number | null,
  micMonophonicAttackTrackedNote: null as string | null,
  micMonophonicAttackPeakVolume: 0,
  micMonophonicFirstDetectedAtMs: null as number | null,
  micPolyphonicDetectorProvider: 'spectrum' as MicPolyphonicDetectorProvider,
  lastMicPolyphonicDetectorProviderUsed: null as MicPolyphonicDetectorProvider | null,
  lastMicPolyphonicDetectorFallbackFrom: null as MicPolyphonicDetectorProvider | null,
  lastMicPolyphonicDetectorWarning: null as string | null,
  micPolyphonicDetectorTelemetryFrames: 0,
  micPolyphonicDetectorTelemetryTotalLatencyMs: 0,
  micPolyphonicDetectorTelemetryMaxLatencyMs: 0,
  micPolyphonicDetectorTelemetryLastLatencyMs: null as number | null,
  micPolyphonicDetectorTelemetryFallbackFrames: 0,
  micPolyphonicDetectorTelemetryWarningFrames: 0,
  micPolyphonicDetectorTelemetryWindowStartedAtMs: 0,
  micPolyphonicDetectorTelemetryLastUiRefreshAtMs: 0,
  preferredMidiInputDeviceId: null as string | null,
  midiAccess: null as MIDIAccess | null,
  midiInput: null as MIDIInput | null,
  isLoadingSamples: false,
  audioCache: {} as Partial<Record<IInstrument['name'], SoundfontPlayer>>, // Loaded soundfont players by instrument
};
